############## The train & val & test set root ##############
# train_file:  ['data/finetune/rsitmd_train.json']
# val_file: 'data/finetune/rsitmd_val.json'
# test_file: 'data/finetune/rsitmd_test.json'
# image_root: '../X-VLM-pytorch/images/rsitmd/'

train_file:  ['../../fs/finetune/rsitmd_train_length_avg_0_7_low_0_95.json']
val_file: '../../fs/finetune/rsitmd_val.json'
test_file: '../../fs/finetune/rsitmd_test.json'
image_root: '../../data/RSITMD/images/'
dataset_kind: 're_ucm'

############## Vision encoder setting ##############
vision_config: 'configs/config_swinT_224.json'  # configs/config_swinT_224.json 'configs/config_swinB_224.json'

# resnet_ckpt: 'data/aid_28-rsp-resnet-50-ckpt.pth' # 'data/aid_28-rsp-resnet-50-ckpt.pth' or 'INS/aid_resnet50.pth'
resnet_ckpt: '../../fs/aid_28-rsp-resnet-50-ckpt.pth'
# resnet_ckpt: '../../fs/best.pt'

finetune_conv: False # whether fintue the conv encoder
use_swin: True  # if use swin, using 'True'
image_res: 224  # no need modify
patch_size: 32   #if use swin, set the patch_size to 32, else 16

############## Text encoder setting ##############
# text_config: 'configs/config_bert.json'
# text_encoder: 'data/bert-base-uncased'
text_config: 'configs/config_bert.json'
text_encoder: '../../fs/bert-base-uncased'

deletion_rate: 0.03 # the rate of random deletion of a word when training

################ Training setting ################
#== no need revise in general
batch_size_train: 128
batch_size_test: 128
batch_size_test_text: 128

# batch_size_train: 135
# batch_size_test: 135
# batch_size_test_text: 135

max_tokens: 47
embed_dim: 512
temp1: 0.07
temp2: 0.07
k_test: 512
beta1: -0.002
beta2: 0.02
alpha_m: 0.95
is_baseline: False  # whether is baseline

############## Other Settings ##############
optimizer: {opt: adamW, lr: 6e-5, weight_decay: 0.01, lr_mult: 2}  # 3e-5 ana 6e-5 are all you need
schedular: {sched: linear, lr: 6e-5, epochs: 20, num_warmup_steps: 0.1} # need to set the epoches, if needed, also lr

################ Model setting  ########################################################################################
#== 1. Representation Alignment, RA                                                                                 ####
use_affil_loss: True # use affil loss
use_scene_loss: True # use scene-adaptive fine-grained perceptual loss
use_triplet_loss: False
scene_factor: 1
center_factor: 1 # if use affil loss, set the center factor                                                         ####
                                                                                                                    ####
#== 2. Fine-Grained Information Supplementation Module, FGIS                                                        ####
img_gcn_step: 2 # modify the number of gcn                                                                          ####
                                                                                                                    ####
#== 3. other parameter                                                                                              ####
dropout_r: 0.2                                                                                                      #### 

########################################################################################################################